### PR TITLE
Minor grammar edit — no change in content.

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Comment by msgilligan** [comment]
@atsticks @keilw Did you guys notice this minor pull request?

**Comment by keilw** [comment]
Yes, but it must not be automatically merged, the API should only have EG Members as authors. Via Patch/Diff somebody from the EG should be able to apply, but we can't just merge it;-)

**Comment by msgilligan** [comment]
I see. I'd say this is more editing than authoring, but I understand the situation. Just thought it might have been missed over the holidays.

So, you would like additional pull requests if I find other issues?

**Comment by keilw** [comment]
At least an issue, but if you find a concrete change, that is fine. Where the diff/patch can be applied manually, it certainly helps.

**Comment by msgilligan** [comment]
Nice work on the Spec, by the way. I've been reviewing it for possible use in some Bitcoin-related projects.

**Comment by keilw** [comment]
Sounds great, please have a look at https://github.com/JavaMoney/javamoney-shelter/tree/master/digital-currency/bitcoin
That started with MtGox, more work to do as that exchange no longer exists, but it shows some nice patterns on how to use it.

Unlike the API or RI/TCK you'd be more then welcome to contribute there or other projects.

**Comment by msgilligan** [comment]
My main interests at this time are:

1. Creating an adapter between JavaMoney and bitcoinj for representing BTC amounts. See [Google groups thread](https://groups.google.com/d/topic/bitcoinj/3de21iQdA0c/discussion).
2. Creating JVM classes for Omni Protocol that can represent BTC and Omni Protocol based currencies. See https://github.com/msgilligan/bitcoin-spock/issues/30.

I guess that might mean implementing the SPI. I'll definitely check out the "Shelter" project.

**Comment by keilw** [comment]
Love to hear your thoughts or input. There pull-requests are welcome and easy to merge. For those who are interested "adopting" the Shelter projects, we also have a special team. Have a look, and if there's anything to pull, we'd see it.

**Comment by msgilligan** [comment]
OK, I created an issue over on "Shelter" for making a Bitcoin SPI, we can move this new discussion over there: https://github.com/JavaMoney/javamoney-shelter/issues/4

**Comment by keilw** [comment]
OK, it neither could nor should be merged here any more, applied those paragraphs that are still there manually.

**Pull request closed without merging**
