### PR TITLE
getNumberType() return Class<? extends Number>

### PR DESCRIPTION
**Pull request by msgilligan**
getNumberType() should provide an explicit guarantee that
the type returned extends Number. So it should return:

Class<? extends Number>

instead of

Class<?>

### CODE REVIEW

**Comment by keilw** [comment]
Sounds reasonable, but especially in the API we can only merge if the PR comes from an EG member. Have you joined the JCP already? 
Please raise a JIRA ticket against the API with above description: http://java.net/jira/browse/javamoney
Thanks.

**Comment by msgilligan** [comment]
I created [JAVAMONEY-154](https://java.net/jira/browse/JAVAMONEY-154) on JIRA.

I joined the JCP website but haven't filed the paperwork to be a full member. I'll do that.

**Comment by keilw** [comment]
Since it's only 3 lines, we will have to do it manually here (based on JIRA ticket that is OK as long as only EG members actually commit) Thanks

**Comment by msgilligan** [comment]
That's fine with me. Note: The PR passes unit tests (which required some mods) but adding the upper bound to the wildcard could affect other modules or user applications. Although, I think it can be argued that if this change does break an app, that it had a bug anyway.

**Comment by otaviojava** [comment]
@keilw I believe this commit is cool, but can we change the API?

**Comment by keilw** [comment]
In a snapshot yes, but it won't go live till MR. However do NOT merge this as only EG members must contribute to API (that's why the JIRA ticket is relevant here, we'll have to close this, but may take issue as inspiration ;-) )

**Comment by msgilligan** [comment]
@keilw @otaviojava Please note my comment on the JIRA issue that I found language in the Spec that explicitly says more than just `<? extends Number>` is supported.

**Comment by msgilligan** [comment]
As I mentioned above and in [JAVAMONEY-154](https://java.net/jira/browse/JAVAMONEY-154), the spec says:

> It explicitly does not constrain the type returned to be a subtype of java.lang.Number to allow alternate implementations to be used.

I think this issue can be closed.

**Pull request closed without merging**
