### PR TITLE
rename ALL CAPS method name to camelCase

### LINKED ISSUE #90: Inconsistent null checks in Monetary
The `null` checks in `javax.money.Monetary` for the singleton SPIs are inconsistent.

`MONETARY_CURRENCIES_SINGLETON_SPI` and `monetaryRoundingsSingletonSpi` can never return `null` yet all of their callers wrap them in a redundant `Optional.ofNullable`.

Additionally the naming conventions are inconsistent, `MONETARY_CURRENCIES_SINGLETON_SPI` is ALL CAPS despite not being final and `monetaryAmountsSingletonSpi`, `monetaryAmountsSingletonQuerySpi` and `monetaryRoundingsSingletonSpi` are camelCase.

### PR DESCRIPTION
**Pull request by freeman0432**
fixes #90

---
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-api/124)

### CODE REVIEW

**Comment by freeman0432** [comment]
Sorry, I am not  JCP member. @keilw ,I didn't expect to bother you.

**Comment by keilw** [comment]
@freeman0432 Sorry to hear, you could join as Associate Member if you like, it is not hard to join and every membership (even for companies) is free.

**Comment by stokito** [comment]
@keilw if the project have such limitation then it should be noted in CONTRIBUTE.md file
https://help.github.com/en/articles/setting-guidelines-for-repository-contributors

**Comment by keilw** [comment]
@stokito This is more or less common knowledge by all JSRs. As Jakarta EE with the former Java EE JSRs moves a large portion away, there are fewer "traditional" JSRs but e.g. https://github.com/jsr107/jsr107spec also does not have a HOWTO. We could create such document for a new release, right now the MR has other priorities.

**Comment by marschall** [comment]
> Thanks, I recall this was a rather static and constant instance, therefore the uppercase. 

It is `static` but a method rather than a field, it should therefore not be ALL_CAPS.

**Comment by marschall** [comment]
This does not fully fix #90. It fixes only one part of #90 namely the method naming that violates Java idioms. It does not remove the redundant `null` checks. I have no issues with the changes as long as

> fixes #90

Is removed from the comment, otherwise GitHub closes #90 when it should not.

**Comment by keilw** [comment]
We also made exceptions where a method represents a constant value e.g. `MetricPrefix.KILO()` in JSR 385. In some cases a semantic meaning goes beyond the simple Java naming conventions.

**Comment by keilw** [comment]
Then let's close this one, @marschall or @stokito  both of you are JCP members already, would you be able to propose another PR that fixes #90 completely?

**Comment by marschall** [comment]
@keilw I submitted #125

**Comment by keilw** [comment]
@marschall Thanks, will check it out soon. Is there a behavioral change the BP might also need? The internals like uppercase I would not call so tragic there, but if it changes anything, that should also be backported.

**Comment by marschall** [comment]
There is no behavioral change. These are private methods and do not impact any user. There might be slightly less `Optional` instances allocated but escape analysis may entirely remove them.
The lambdas itself are non-capturing and should not allocate.

**Comment by keilw** [comment]
Ok thanks, then it may be less relevant to backport them.

**Comment by freeman0432** [comment]
@keilw, thank you for your advice. I have joined the JCP

**Comment by keilw** [comment]
@freeman0432 Thanks a lot, we'll ask the PMO to add contributors who helped with the JSR until the MR1, if you want and your name is already listed in https://jcp.org/en/participation/members/ (it usually takes a bit after you submitted everything) we could also ask to add contributors. Otherwise everyone is welcom to join a follow-up JSR where contributors can also self-nominate (right now in Maintenance phase this is only possible by asking the PMO)

**Comment by freeman0432** [comment]
@keilw, excuse me! I have submitted my profile for a few days. But the note is "Profile information in JCP DB is updated after JCP PMO review." What should I do?

**Comment by keilw** [comment]
They will take a bit of time, no worries. Especially in Summer

**Comment by freeman0432** [comment]
Thanks  a lot.

**Comment by freeman0432** [comment]
@keilw, thanks  a lot.

**Comment by freeman0432** [comment]
@keilw Help me.I send email to admin@jcp.org, no one reply me.

**Comment by keilw** [comment]
They seem to be on vacation, we asked to finalize JSR 385 a few days ago and there was also no response. Plus Oracle does its house conference in less than a month, so probably not much activity before then ;-/

**Comment by freeman0432** [comment]
It turned out to be the case, thank you very much. Then I will wait for their holiday to end.

**Comment by freeman0432** [comment]
@keilw 
I received an email notifying that the AMA has been completed, but my name is not listed at https://jcp.org/en/participation/members/.
Can you merge my PR now?

**Comment by keilw** [comment]
The PR is closed and has been done (the relevant parts) by others like @thodorisbais I believe.

**Comment by keilw** [comment]
If it hasn't could you forward the mail from PMO to werner@javamoney.org please?

**Comment by freeman0432** [comment]
Sorry, my expression is a bit problematic. I mean, can I submit a new RP the next time I contribute code?

**Comment by keilw** [comment]
Yes, if they have you in their system, it should be OK.

**Pull request closed without merging**
