### PR TITLE
Javadoc fixes

### PR DESCRIPTION
**Pull request by marschall**
I get a lot of Javadoc warnings, this commit fixes some of them.

---
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-api/76)

### CODE REVIEW

**Comment by keilw** [comment]
@marschall Thanks, are you a JCP Member already? We can only merge API or RI PRs by JCP members, Associate Membership is sufficient. Ask me, @otaviojava or @atsticks for help if you wish to join. It is free and in most cases processed relatively fast by JCP PMO.

**Comment by marschall** [comment]
@keilw I believe I was a JCP member at one point but the process was really annoying. I believe I missed my renewal at one point. I there somewhere an an easy step by step guide what I need to do?

**Comment by marschall** [comment]
@keilw I'll try to reactive my membership

**Comment by marschall** [comment]
I just signed the JCP Associate Membership Agreement, my profile hasn't yet been updated and Oracle hasn't signed yet.

**Comment by marschall** [comment]
Still no change, should I send a mail to admin@jcp.org and ask for updates?

**Comment by keilw** [comment]
Yes, and maybe also pmo@jcp.org. They are down to just a handful of people after Jakarta EE left for Eclipse, and I know at least Heather was just travelling to a F2F and probably gave a speech at JPrime, so bare with them till after the weekend.

**Comment by keilw** [comment]
If you're on Twitter, ask https://twitter.com/adoptajsr, there is also this Oracle community page: https://community.oracle.com/community/java/jcp/adopt-a-jsr, but it is likely affected by the same shortage of people as all the others. It's worth a try, they should not turn you down if you want to help adopting a JSR ;-)

**Comment by marschall** [comment]
Still nothing.

**Comment by keilw** [comment]
I'll ask them.

**Comment by keilw** [comment]
Thanks for the update, I guess it'll take a little but your name should show up here https://jcp.org/en/participation/members/M soon.

**Comment by marschall** [comment]
Yeah, under jcp.org -> My Profile -> View Profile still shows
```
Entity: Not a JCP Member
```
but I did get a signed PDF from Oracle.

**Comment by keilw** [comment]
That's weird, but given you already contributed to the RI on several occasions not sure, if we'll wait much longer here. I can ask Harold again.

**Comment by keilw** [comment]
Great, guess Harold came back from his holiday.

**Comment by keilw** [comment]
Could you propose this one again please @marschall because with all the different PRs being open for so long, this out of all 4 had a conflict? Thanks

**Comment by marschall** [comment]
Sure, no problem

**Pull request closed without merging**
