### PR TITLE
Throw an exception on a never null method when result set is empty

### PR DESCRIPTION
**Pull request by freeman0432**
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-api/127)

### CODE REVIEW

**Comment by keilw** [comment]
Is @freeman0432 a JCP member already, at least an Associate?

**Comment by freeman0432** [comment]
> Thanks, before we merge it, is @freeman0432 listed as JCP member in https://jcp.org/en/participation/members already?

**Comment by freeman0432** [comment]
> Thanks, before we merge it, is @freeman0432 listed as JCP member in https://jcp.org/en/participation/members already?
My name is Hsin, Vincent in the list.

**Comment by freeman0432** [comment]
@

> Thanks, before we merge it, is @freeman0432 listed as JCP member in https://jcp.org/en/participation/members already?

My name is Hsin, Vincent in the list.
[AMA-VincentHsin.pdf](https://github.com/JavaMoney/jsr354-api/files/3904162/AMA-VincentHsin.pdf)
[Summary.pdf](https://github.com/JavaMoney/jsr354-api/files/3904163/Summary.pdf)

**Comment by keilw** [comment]
Great, thanks, I saw it.

**Pull request merged**
